### ISSUE TITLE
PHP Fatal error:  Call to undefined function lzf_decompress()

### ISSUE THREAD

**Issue by brentwpeterson** [colinmollenhour/Cm_Cache_Backend_Redis#105] opened 2016-04-20 16:49 UTC
Getting this error when trying to run REDIS

PHP Fatal error:  Call to undefined function lzf_decompress() in app/code/community/Cm/Cache/Backend/Redis.php on line 863

I have confirmed that the php lzf module  is loaded.

Magento 1.12

**Comment by colinmollenhour** [comment] 2016-04-20 17:16
There is no other explanation that I know of other than lzf must not be installed.. Are you sure it is enabled in the environment in which you are getting the error? E.g. PHP on Debian/Ubuntu has separate directories for cli, apache2, fpm that contain symlinks to the PHP modules. If lzf is shown as enabled in phpinfo() then I don't see how this error can occur.

**Comment by colinmollenhour** [comment] 2016-04-20 17:18
Looks like a duplicate of your previous ticket #104.. I thought I was experiencing deja vu. :)
Anyway, I don't see how this can be a Cm_Cache_Backend_Redis bug.

**Closed** 2017-02-28 15:28 UTC
